// Generated by Copilot
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export function middleware(request: NextRequest) {
  const authToken = request.cookies.get("auth_token")?.value;
  const pathname = request.nextUrl.pathname;

  const isAuthRoute =
    pathname.startsWith("/dashboard") ||
    pathname.startsWith("/usuarios") ||
    pathname.startsWith("/clientes") ||
    pathname.startsWith("/facturas");

  // Redirige solo a rutas internas conocidas
  if (isAuthRoute && !authToken) {
    return NextResponse.redirect(new URL("/login", request.url));
  }

  if (
    authToken &&
    (pathname === "/login" || pathname === "/register")
  ) {
    return NextResponse.redirect(new URL("/dashboard", request.url));
  }

  return NextResponse.next();
}

// See "Matching Paths" below to learn more
export const config = {
  matcher: [
    "/dashboard/:path*",
    "/usuarios/:path*",
    "/clientes/:path*",
    "/facturas/:path*",
    "/login",
    "/register"
  ],
}
