// Generated by Copilot
import { Users, FileText, User } from "lucide-react";
import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  darkMode: 'class',
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./public/index.html"
  ],
  theme: {
    extend: {}
  },
  plugins: [tailwindcssAnimate],
};

export default config;
export const navigationItems = [
	{ name: "Usuarios", href: "/usuarios", icon: User, requiresAuth: true },
	{ name: "Clientes", href: "/clientes", icon: Users, requiresAuth: true },
	{ name: "Facturas", href: "/facturas", icon: FileText, requiresAuth: true },
];
