// Generated by Copilot
import { render, screen } from '@testing-library/react'
import { Button } from './button'

describe('Button', () => {
  it('renderiza el texto correctamente', () => {
    render(<Button>Click me</Button>)
    expect(screen.getByText('Click me')).toBeInTheDocument()
  })
})
